security:
    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN : ROLE_SUPER_ADMIN
    access_control:
        - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login
                default_target_path: admin_dash
                always_use_default_target_path: true
            logout:
                path: logout
                target: /

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12